# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lovely',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/lovely',
                'lib_path': 'lovely'},
  'syms': {'lovely.core': {'lovely.core.foo': ('core.html#foo', 'lovely/core.py')}}}