# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03b_utils.misc.ipynb.

# %% auto #0
__all__ = ['to_numpy']

# %% ../../nbs/03b_utils.misc.ipynb #89be7f95
import numpy as np
import torch

# %% ../../nbs/03b_utils.misc.ipynb #9f6f5585
def to_numpy(t: torch.Tensor) -> np.ndarray:
    t = t.detach().cpu()
    # .numpy() can't properly handle bf16 or float8 variants.
    if t.dtype is torch.bfloat16 or (t.is_floating_point() and t.element_size() < 2):
        t = t.to(torch.float32)
    return t.numpy()
