# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lovely',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/lovely',
                'lib_path': 'lovely_tensors'},
  'syms': { 'lovely_tensors.tensors': { 'lovely_tensors.tensors.__PrinterOptions': ( 'tensors.html#__printeroptions',
                                                                                     'lovely_tensors/tensors.py'),
                                        'lovely_tensors.tensors.lovely': ('tensors.html#lovely', 'lovely_tensors/tensors.py'),
                                        'lovely_tensors.tensors.monkey_patch': ('tensors.html#monkey_patch', 'lovely_tensors/tensors.py'),
                                        'lovely_tensors.tensors.sci_mode': ('tensors.html#sci_mode', 'lovely_tensors/tensors.py'),
                                        'lovely_tensors.tensors.show_rgb': ('tensors.html#show_rgb', 'lovely_tensors/tensors.py'),
                                        'lovely_tensors.tensors.space_join': ('tensors.html#space_join', 'lovely_tensors/tensors.py'),
                                        'lovely_tensors.tensors.tensor_str': ('tensors.html#tensor_str', 'lovely_tensors/tensors.py')}}}